# docker-compose.yml — определяет сервисы для разработки и тестирования.

# Запускаем только в prod, разработке docker-compose не нужен.
services:
  postgres-db:
    image: postgres:latest
    container_name: bank-postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_bank:/var/lib/postgresql/data
    networks:
      - bank-network


  bank-service:
    build: .
    image: bank-service
    container_name: bank-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - bank-network

volumes:
  postgres_data_bank:

networks:
  bank-network:
