# docker-compose.yml — определяет сервисы для разработки и тестирования.

# Запускаем только в prod, разработке docker-compose не нужен.
services:
  postgres-db:
    image: postgres:latest
    container_name: bank-postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_bank:/var/lib/postgresql/data
    networks:
      - bank-network


  bank-service:
    image: bank-service
    container_name: bank-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - bank-network

volumes:
  postgres_data_bank:

# Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.
