spring:
  application:
    name: BankCardsManagement
  main:
    banner-mode: off
  web:
    resources:
      add-mappings: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,openapi,swagger-ui
