spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

security:
  jwt:
    secret: "ae0d1c4bc64c43a798224f87721c5890909d59bdf186429a9c9ffc5c6356f5647e13a0975aa54d0880bccd"
    duration: 60
  admin:
    secret: "$2a$10$H9c83bpIGYUkxmjh7WkLxuBUOj.v4SQ4cDELERm56fUxyR4lDK0wG"
  card-number:
    master-key: "DYw3ZcE45osN4T0FHNusKA=="
    hmac: "ZWVkYWVlZmItZWVjZi00Yjc1LTkwZWUtNGEyYzkxN2YyY2M4Y2I4MjQzYzEtMTZkNi00YzM0LTgwOTMtNmY1ZmQxNDQ0YTg5"

card:
  months-until-expires: 24